name: Bash Set

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: set -e
        if: false
        run: |
          # set -e
          ls
          ls -l missing_folder
          mkdir existing_folder
          ls -l existing_folder
